#--------Flask Config------------
DEBUG = True
SECRET_KEY = 'b7614af64f2f1c6fce84408fd05c946c6426fcdd03b48b60'

#--------DB Config------------
MONGODB_SETTINGS = {
'DB':  'DB_NAME',
'USERNAME': 'DB_USERNAME',
'PASSWORD': 'DB_PASSWORD',
'HOST': 'HOST_LINK',
'PORT': PORT
}

#--------Mail Config---------
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'YOUR_EMAIL'
MAIL_PASSWORD = 'YOUR_EMAIL_PASSWORD'

#-----------Flask-secuirty configs----------------

#Feature Flags
SECURITY_REGISTERABLE = True
SECURITY_CHANGEABLE = True
SECURITY_CONFIRMABLE = True
SECURITY_RECOVERABLE = True
SECURITY_TRACKABLE = True
SECURITY_PASSWORDLESS = False

#Core
SECURITY_BLUEPRINT_NAME = 'security'
SECURITY_URL_PREFIX = None
SECURITY_FLASH_MESSAGES = True
SECURITY_PASSWORD_HASH = 'sha512_crypt' #Recommended values for production systems are bcrypt, sha512_crypt, or pbkdf2_sha512
SECURITY_PASSWORD_SALT = "randomsaltvaluehere"
SECURITY_EMAIL_SENDER = 'no-reply@redbrick.io'
SECURITY_TOKEN_AUTHENTICATION_KEY = 'auth_token'
SECURITY_TOKEN_AUTHENTICATION_HEADER = 'Authentication-Token'
SECURITY_DEFAULT_HTTP_AUTH_REALM = 'Login Required'

#Views/Urls
SECURITY_REGISTER_URL = '/register'
SECURITY_LOGIN_URL = '/login'
SECURITY_LOGOUT_URL = '/logout'
SECURITY_CHANGE_URL = '/change-password'
SECURITY_RESET_URL = '/reset'
SECURITY_CONFIRM_URL = '/confirm'
SECURITY_POST_LOGIN_VIEW = '/'
SECURITY_POST_LOGOUT_VIEW = '/'
SECURITY_CONFIRM_ERROR_VIEW = None
SECURITY_POST_REGISTER_VIEW = SECURITY_POST_LOGIN_VIEW
SECURITY_POST_CONFIRM_VIEW = SECURITY_POST_LOGIN_VIEW
SECURITY_POST_RESET_VIEW = SECURITY_POST_LOGIN_VIEW
SECURITY_POST_CHANGE_VIEW = SECURITY_POST_LOGIN_VIEW
SECURITY_UNAUTHORIZED_VIEW = None

#Template Paths
SECURITY_FORGOT_PASSWORD_TEMPLATE = 'security/forgot_password.html'
SECURITY_LOGIN_USER_TEMPLATE = 'security/login_user.html'
SECURITY_REGISTER_USER_TEMPLATE = 'security/register_user.html'
SECURITY_RESET_PASSWORD_TEMPLATE = 'security/reset_password.html'
SECURITY_CHANGE_PASSWORD_TEMPLATE = 'security/change_password.html'
SECURITY_SEND_CONFIRMATION_TEMPLATE = 'security/send_confirmation.html'
SECURITY_SEND_LOGIN_TEMPLATE = 'security/send_login.html'

#Email
SECURITY_EMAIL_SUBJECT_REGISTER = 'Welcome'
SECURITY_EMAIL_SUBJECT_PASSWORDLESS = 'Login instructions'
SECURITY_EMAIL_SUBJECT_PASSWORD_NOTICE = 'Your password has been reset'
SECURITY_EMAIL_SUBJECT_PASSWORD_RESET = 'Password reset instructions'
SECURITY_EMAIL_SUBJECT_PASSWORD_CHANGE_NOTICE = 'Your password has been changed'
SECURITY_EMAIL_SUBJECT_CONFIRM = 'Please confirm your email'

#Miscellaneous
SECURITY_SEND_REGISTER_EMAIL =  True
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = True
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL =     True
SECURITY_CONFIRM_EMAIL_WITHIN = '5 days'
SECURITY_RESET_PASSWORD_WITHIN = '5 days'
SECURITY_LOGIN_WITHIN =   '1 days' #only used when the passwordless login feature is enabled
SECURITY_LOGIN_WITHOUT_CONFIRMATION     = 'False' #only used when the value of SECURITY_CONFIRMABLE is set to True.
SECURITY_CONFIRM_SALT = 'confirm-salt'
SECURITY_RESET_SALT = 'reset-salt'
SECURITY_LOGIN_SALT = 'login-salt'
SECURITY_REMEMBER_SALT = 'remember-salt'
SECURITY_DEFAULT_REMEMBER_ME = False
